name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        ls

    - name: Build the package
      working-directory: /home/runner/work/guardrails/guardrails/guardrails_sdk
      run: python -m build

    # Step 5: Publish to PyPI
    - name: Publish to PyPI
      working-directory: /home/runner/work/guardrails/guardrails/guardrails_sdk
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: python -m twine upload dist/*